name: Update docs

on:
  push:
    branches: [ 'main' ]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' 
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate documentation
        run: npm run docs-latest && npm run docs-stable
      - name: Check for documentation changes
        id: check_changes
        run: |
          if [[ -n "$(git diff kaituo/pages-only HEAD -- pages/)" ]]; then
            echo "Documentation changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No documentation changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Get latest commit SHA
        id: get_commit_sha
        run: |
          COMMIT_SHA=$(git log -1 --pretty=%H) # Get latest commit SHA (full hash)
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "Latest commit SHA: $COMMIT_SHA"
      - name: Commit and Push to pages-only branch
        if: steps.check_changes.outputs.has_changes == 'true' # Only run if changes were detected
        run: |
          git config user.email "genai-sdk-bot@google.com"
          git config user.name "genai-sdk-bot"
          git add pages/
          COMMIT_MESSAGE="docs: Update docs from merged commit: ${{ steps.get_commit_sha.outputs.commit_sha }}"
          echo "Commit message: $COMMIT_MESSAGE"
          git commit -m "$COMMIT_MESSAGE" --allow-empty
          git push --force origin HEAD:pages-only
